name: Testes CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm run test

      - name: Notificar Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"CI executado com sucesso 🚀\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}